// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdktdkzvfyprngnvckzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka3Rka3p2Znlwcm5nbnZja3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzY5NDYsImV4cCI6MjA2ODAxMjk0Nn0.gBQ32IWPTmRWHdT8wiaLnBY4yRZCH4xXic0jY_PmoEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});